// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

    #include "lv_i18n.h"
#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

// SCREEN: ui_LogoScreen
void ui_LogoScreen_screen_init(void);
void ui_event_LogoScreen( lv_event_t * e);
extern lv_obj_t *ui_LogoScreen;
extern lv_obj_t *ui_SCLogo;
// CUSTOM VARIABLES

// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t *ui_MainScreen;
void ui_event_PanelFan1( lv_event_t * e);
extern lv_obj_t *ui_PanelFan1;
extern lv_obj_t *ui_ArcFan1;
extern lv_obj_t *ui_LabelFan1;
extern lv_obj_t *ui_ValueFan1;
extern lv_obj_t *ui_RPMFan1;
extern lv_obj_t *ui_VoltagesLabel;
void ui_event_PanelFan2( lv_event_t * e);
extern lv_obj_t *ui_PanelFan2;
extern lv_obj_t *ui_ArcFan2;
extern lv_obj_t *ui_LabelFan2;
extern lv_obj_t *ui_ValueFan2;
extern lv_obj_t *ui_RPMFan2;
extern lv_obj_t *ui_PanelFan3;
extern lv_obj_t *ui_ArcFan3;
extern lv_obj_t *ui_LabelPump1;
extern lv_obj_t *ui_ValueFan3;
extern lv_obj_t *ui_RPMFan3;
extern lv_obj_t *ui_PanelFan4;
extern lv_obj_t *ui_ArcFan4;
extern lv_obj_t *ui_LabelPump2;
extern lv_obj_t *ui_ValueFan4;
extern lv_obj_t *ui_RPMFan4;
extern lv_obj_t *ui_Panel12Volts;
extern lv_obj_t *ui_Volts12Value;
extern lv_obj_t *ui_Volts12Label;
extern lv_obj_t *ui_Panel5Volts;
extern lv_obj_t *ui_Volts5Value;
extern lv_obj_t *ui_Volts5Label;
extern lv_obj_t *ui_Panel3V3Volts;
extern lv_obj_t *ui_Volts3V3Value;
extern lv_obj_t *ui_Volts3V3Label;
void ui_event_PanelAmbient1( lv_event_t * e);
extern lv_obj_t *ui_PanelAmbient1;
extern lv_obj_t *ui_Ambient1Label;
extern lv_obj_t *ui_Temp3Value;
extern lv_obj_t *ui_Temp3Label;
void ui_event_PanelAmbient2( lv_event_t * e);
extern lv_obj_t *ui_PanelAmbient2;
extern lv_obj_t *ui_Ambient2Label;
extern lv_obj_t *ui_Temp4Value;
extern lv_obj_t *ui_Temp4Label;
extern lv_obj_t *ui_PanelT1;
extern lv_obj_t *ui_ArcT1;
extern lv_obj_t *ui_LabelT1;
extern lv_obj_t *ui_ValueT1;
extern lv_obj_t *ui_MetricT1;
extern lv_obj_t *ui_PanelT2;
extern lv_obj_t *ui_ArcT2;
extern lv_obj_t *ui_LabelT2;
extern lv_obj_t *ui_ValueT2;
extern lv_obj_t *ui_RPMT2;
void ui_event_SettingsButton( lv_event_t * e);
extern lv_obj_t *ui_SettingsButton;
extern lv_obj_t *ui_SettingsLabel;
extern lv_obj_t *ui_TapToSwitchLabel;
// CUSTOM VARIABLES

// SCREEN: ui_LedSettingsScreen
void ui_LedSettingsScreen_screen_init(void);
extern lv_obj_t *ui_LedSettingsScreen;
void ui_event_NextButton( lv_event_t * e);
extern lv_obj_t *ui_NextButton;
extern lv_obj_t *ui_NextLabel;
extern lv_obj_t *ui_RGBPanelTitle;
extern lv_obj_t *ui_LEDEffectLabel;
void ui_event_LEDEffectDropdown( lv_event_t * e);
extern lv_obj_t *ui_LEDEffectDropdown;
extern lv_obj_t *ui_NumOfLEDsLabel;
void ui_event_NumOfLEDs( lv_event_t * e);
extern lv_obj_t *ui_NumOfLEDs;
extern lv_obj_t *ui_RGBStripePanel;
void ui_event_RedSlider( lv_event_t * e);
extern lv_obj_t *ui_RedSlider;
void ui_event_GreenSlider( lv_event_t * e);
extern lv_obj_t *ui_GreenSlider;
void ui_event_BlueSlider( lv_event_t * e);
extern lv_obj_t *ui_BlueSlider;
extern lv_obj_t *ui_RedSliderValue;
extern lv_obj_t *ui_GreenSliderValue;
extern lv_obj_t *ui_BlueSliderValue;
extern lv_obj_t *ui_TempSensorSelectorPanel;
extern lv_obj_t *ui_TempSensorListLabel;
void ui_event_TempSensorListDropdown( lv_event_t * e);
extern lv_obj_t *ui_TempSensorListDropdown;
void ui_event_BackButton( lv_event_t * e);
extern lv_obj_t *ui_BackButton;
extern lv_obj_t *ui_BackLabel;
void ui_event_SaveButton( lv_event_t * e);
extern lv_obj_t *ui_SaveButton;
extern lv_obj_t *ui_SaveLabel;
extern lv_obj_t *ui_LEDSettingsScreenKB;
// CUSTOM VARIABLES

// SCREEN: ui_AlertSettingsScreen
void ui_AlertSettingsScreen_screen_init(void);
extern lv_obj_t *ui_AlertSettingsScreen;
extern lv_obj_t *ui_TresholdsPanel;
extern lv_obj_t *ui_MinRPMAlertLabel;
extern lv_obj_t *ui_Fan1Label;
void ui_event_Fan1Min( lv_event_t * e);
extern lv_obj_t *ui_Fan1Min;
extern lv_obj_t *ui_Fan2Label;
void ui_event_Fan2Min( lv_event_t * e);
extern lv_obj_t *ui_Fan2Min;
extern lv_obj_t *ui_Pump1Label;
void ui_event_Pump1Min( lv_event_t * e);
extern lv_obj_t *ui_Pump1Min;
extern lv_obj_t *ui_Pump2Label;
void ui_event_Pump2Min( lv_event_t * e);
extern lv_obj_t *ui_Pump2Min;
void ui_event_Fan1LabelDropdown( lv_event_t * e);
extern lv_obj_t *ui_Fan1LabelDropdown;
void ui_event_Fan2LabelDropdown( lv_event_t * e);
extern lv_obj_t *ui_Fan2LabelDropdown;
void ui_event_Pump1LabelDropdown( lv_event_t * e);
extern lv_obj_t *ui_Pump1LabelDropdown;
void ui_event_Pump2LabelDropdown( lv_event_t * e);
extern lv_obj_t *ui_Pump2LabelDropdown;
extern lv_obj_t *ui_Temp2Label;
extern lv_obj_t *ui_Temp1Label;
void ui_event_Temp1LabelDropdown( lv_event_t * e);
extern lv_obj_t *ui_Temp1LabelDropdown;
void ui_event_Temp2LabelDropdown( lv_event_t * e);
extern lv_obj_t *ui_Temp2LabelDropdown;
extern lv_obj_t *ui_RGBPanel2;
extern lv_obj_t *ui_RGBPanel2Title;
void ui_event_Colorwheel2( lv_event_t * e);
extern lv_obj_t *ui_Colorwheel2;
void ui_event_EnableLedAlert( lv_event_t * e);
extern lv_obj_t *ui_EnableLedAlert;
void ui_event_NextButton1( lv_event_t * e);
extern lv_obj_t *ui_NextButton1;
extern lv_obj_t *ui_NextLabel1;
void ui_event_BackButton2( lv_event_t * e);
extern lv_obj_t *ui_BackButton2;
extern lv_obj_t *ui_BackLabel2;
void ui_event_SaveButton2( lv_event_t * e);
extern lv_obj_t *ui_SaveButton2;
extern lv_obj_t *ui_SaveLabel2;
extern lv_obj_t *ui_AlertSettingsScreenKB;
// CUSTOM VARIABLES

// SCREEN: ui_SettingsScreen
void ui_SettingsScreen_screen_init(void);
extern lv_obj_t *ui_SettingsScreen;
extern lv_obj_t *ui_ThemeLabel;
void ui_event_BgDropdown( lv_event_t * e);
extern lv_obj_t *ui_BgDropdown;
void ui_event_FlipScreenCheckBox( lv_event_t * e);
extern lv_obj_t *ui_FlipScreenCheckBox;
void ui_event_BackButton4( lv_event_t * e);
extern lv_obj_t *ui_BackButton4;
extern lv_obj_t *ui_BackLabel5;
extern lv_obj_t *ui_RGBPanel2Title2;
void ui_event_SaveButton3( lv_event_t * e);
extern lv_obj_t *ui_SaveButton3;
extern lv_obj_t *ui_SaveLabel3;
void ui_event_NextButton3( lv_event_t * e);
extern lv_obj_t *ui_NextButton3;
extern lv_obj_t *ui_NextLabel3;
void ui_event_ThemeDropdown( lv_event_t * e);
extern lv_obj_t *ui_ThemeDropdown;
extern lv_obj_t *ui_ColorThemeLabel;
// CUSTOM VARIABLES

// SCREEN: ui_AboutScreen
void ui_AboutScreen_screen_init(void);
extern lv_obj_t *ui_AboutScreen;
extern lv_obj_t *ui_FWLabel;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_AboutLabel;
extern lv_obj_t *ui_GithubURLLabel;
extern lv_obj_t *ui_Label3;
void ui_event_BackButton1( lv_event_t * e);
extern lv_obj_t *ui_BackButton1;
extern lv_obj_t *ui_BackLabel1;
// CUSTOM VARIABLES

// SCREEN: ui_FanControllerScreen
void ui_FanControllerScreen_screen_init(void);
extern lv_obj_t *ui_FanControllerScreen;
void ui_event_PWM1Arc( lv_event_t * e);
extern lv_obj_t *ui_PWM1Arc;
void ui_event_PWM2Arc( lv_event_t * e);
extern lv_obj_t *ui_PWM2Arc;
extern lv_obj_t *ui_PWM1Percent;
extern lv_obj_t *ui_PWM2Percent;
extern lv_obj_t *ui_PWM1MaxLabel;
extern lv_obj_t *ui_PWM2MaxLabel;
extern lv_obj_t *ui_PWM1ZeroLabel;
extern lv_obj_t *ui_PWM1RPMValueLabel;
extern lv_obj_t *ui_PWM2RPMValueLabel;
void ui_event_BackButton5( lv_event_t * e);
extern lv_obj_t *ui_BackButton5;
extern lv_obj_t *ui_BackLabel4;
void ui_event_SaveButton4( lv_event_t * e);
extern lv_obj_t *ui_SaveButton4;
extern lv_obj_t *ui_SaveLabel4;
extern lv_obj_t *ui_PWM1LabelFan;
extern lv_obj_t *ui_PWM2LabelFan;
extern lv_obj_t *ui_PWM1AutoControl;
extern lv_obj_t *ui_Container1;
extern lv_obj_t *ui_PWM2AutoControl;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_sclogosmall_png);   // assets/sclogosmall.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
