// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_TEXT 0
#define UI_THEME_COLOR_LABELTEXT 1
#define UI_THEME_COLOR_DROPDOWNBG 2
#define UI_THEME_COLOR_BUTTONBG 3
#define UI_THEME_COLOR_BORDERBG 4

#define UI_THEME_DEFAULT 0

#define UI_THEME_THEME1 1

#define UI_THEME_THEME2 2

extern const ui_theme_variable_t _ui_theme_color_TEXT[3];
extern const ui_theme_variable_t _ui_theme_alpha_TEXT[3];

extern const ui_theme_variable_t _ui_theme_color_LABELTEXT[3];
extern const ui_theme_variable_t _ui_theme_alpha_LABELTEXT[3];

extern const ui_theme_variable_t _ui_theme_color_DROPDOWNBG[3];
extern const ui_theme_variable_t _ui_theme_alpha_DROPDOWNBG[3];

extern const ui_theme_variable_t _ui_theme_color_BUTTONBG[3];
extern const ui_theme_variable_t _ui_theme_alpha_BUTTONBG[3];

extern const ui_theme_variable_t _ui_theme_color_BORDERBG[3];
extern const ui_theme_variable_t _ui_theme_alpha_BORDERBG[3];

extern const uint32_t* ui_theme_colors[3];
extern const uint8_t* ui_theme_alphas[3];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
