// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_AboutScreen_screen_init(void)
{
ui_AboutScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_AboutScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_AboutScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AboutScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FWLabel = lv_label_create(ui_AboutScreen);
lv_obj_set_width( ui_FWLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FWLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FWLabel, 187 );
lv_obj_set_y( ui_FWLabel, 133 );
lv_obj_set_align( ui_FWLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_FWLabel,"ESP32S3 N16R2\nV1-20241104");
lv_obj_set_style_text_color(ui_FWLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_FWLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_FWLabel, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel3 = lv_obj_create(ui_AboutScreen);
lv_obj_set_width( ui_Panel3, 360);
lv_obj_set_height( ui_Panel3, 200);
lv_obj_set_x( ui_Panel3, 0 );
lv_obj_set_y( ui_Panel3, -30 );
lv_obj_set_align( ui_Panel3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Panel3, LV_BORDER_SIDE_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AboutLabel = lv_label_create(ui_Panel3);
lv_obj_set_width( ui_AboutLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AboutLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_AboutLabel, 0 );
lv_obj_set_y( ui_AboutLabel, 10 );
lv_obj_set_align( ui_AboutLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_AboutLabel,"by\nSINGULARITY COMPUTERS");
ui_object_set_themeable_style_property(ui_AboutLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TEXT);
ui_object_set_themeable_style_property(ui_AboutLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TEXT);
lv_obj_set_style_text_align(ui_AboutLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_GithubURLLabel = lv_label_create(ui_Panel3);
lv_obj_set_width( ui_GithubURLLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_GithubURLLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_GithubURLLabel, 9 );
lv_obj_set_y( ui_GithubURLLabel, 63 );
lv_obj_set_align( ui_GithubURLLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_GithubURLLabel,"https://singularitycomputers.com\nhttps://github.com/SingularityComputers");
lv_obj_set_style_text_color(ui_GithubURLLabel, lv_color_hex(0xA5A5A5), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_GithubURLLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_GithubURLLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_Panel3);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, 0 );
lv_obj_set_y( ui_Label3, -32 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"FanGuardian");
ui_object_set_themeable_style_property(ui_Label3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TEXT);
ui_object_set_themeable_style_property(ui_Label3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TEXT);
lv_obj_set_style_text_letter_space(ui_Label3, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Label3, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BackButton1 = lv_btn_create(ui_AboutScreen);
lv_obj_set_width( ui_BackButton1, 100);
lv_obj_set_height( ui_BackButton1, 32);
lv_obj_set_x( ui_BackButton1, -183 );
lv_obj_set_y( ui_BackButton1, 132 );
lv_obj_set_align( ui_BackButton1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BackButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BackButton1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_BackButton1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_BUTTONBG);
ui_object_set_themeable_style_property(ui_BackButton1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_BUTTONBG);
ui_object_set_themeable_style_property(ui_BackButton1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_BORDERBG);
ui_object_set_themeable_style_property(ui_BackButton1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_BORDERBG);
lv_obj_set_style_border_width(ui_BackButton1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_BackButton1, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_BackButton1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_BackButton1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_BackButton1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BackButton1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_BackButton1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_BackButton1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_BackButton1, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_BackButton1, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BackButton1, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BackLabel1 = lv_label_create(ui_BackButton1);
lv_obj_set_width( ui_BackLabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BackLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_BackLabel1, LV_ALIGN_CENTER );
lv_label_set_text(ui_BackLabel1,"BACK");
ui_object_set_themeable_style_property(ui_BackLabel1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TEXT);
ui_object_set_themeable_style_property(ui_BackLabel1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TEXT);

lv_obj_add_event_cb(ui_BackLabel1, ui_event_BackLabel1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BackButton1, ui_event_BackButton1, LV_EVENT_ALL, NULL);

}
