// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_FanControllerScreen_screen_init(void)
{
ui_FanControllerScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_FanControllerScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_FanControllerScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_FanControllerScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PWM1Arc = lv_arc_create(ui_FanControllerScreen);
lv_obj_set_width( ui_PWM1Arc, 175);
lv_obj_set_height( ui_PWM1Arc, 174);
lv_obj_set_x( ui_PWM1Arc, -142 );
lv_obj_set_y( ui_PWM1Arc, -20 );
lv_obj_set_align( ui_PWM1Arc, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PWM1Arc, LV_OBJ_FLAG_PRESS_LOCK );    /// Flags
lv_obj_set_scrollbar_mode(ui_PWM1Arc, LV_SCROLLBAR_MODE_OFF);
lv_arc_set_value(ui_PWM1Arc, 25);
lv_arc_set_bg_angles(ui_PWM1Arc,135,15);
lv_obj_set_style_arc_color(ui_PWM1Arc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_PWM1Arc, 80, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_PWM1Arc, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_PWM1Arc, false, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_pad_left(ui_PWM1Arc, 4, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PWM1Arc, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PWM1Arc, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PWM1Arc, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_PWM1Arc, lv_color_hex(0x6AFF00), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_PWM1Arc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_PWM1Arc, 12, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_PWM1Arc, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_PWM1Arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PWM1Arc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_PWM2Arc = lv_arc_create(ui_FanControllerScreen);
lv_obj_set_width( ui_PWM2Arc, 175);
lv_obj_set_height( ui_PWM2Arc, 174);
lv_obj_set_x( ui_PWM2Arc, 103 );
lv_obj_set_y( ui_PWM2Arc, -20 );
lv_obj_set_align( ui_PWM2Arc, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PWM2Arc, LV_OBJ_FLAG_PRESS_LOCK );    /// Flags
lv_obj_set_scrollbar_mode(ui_PWM2Arc, LV_SCROLLBAR_MODE_OFF);
lv_arc_set_value(ui_PWM2Arc, 50);
lv_arc_set_bg_angles(ui_PWM2Arc,135,15);
lv_obj_set_style_arc_color(ui_PWM2Arc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_PWM2Arc, 80, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_PWM2Arc, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_PWM2Arc, false, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_pad_left(ui_PWM2Arc, 4, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PWM2Arc, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PWM2Arc, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PWM2Arc, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_PWM2Arc, lv_color_hex(0x6AFF00), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_PWM2Arc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_PWM2Arc, 12, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_PWM2Arc, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_PWM2Arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PWM2Arc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_PWM1Percent = lv_label_create(ui_FanControllerScreen);
lv_obj_set_width( ui_PWM1Percent, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PWM1Percent, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PWM1Percent, -142 );
lv_obj_set_y( ui_PWM1Percent, -48 );
lv_obj_set_align( ui_PWM1Percent, LV_ALIGN_CENTER );
lv_label_set_text(ui_PWM1Percent,"25%");
lv_obj_set_style_text_color(ui_PWM1Percent, lv_color_hex(0xEDEDED), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PWM1Percent, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PWM1Percent, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PWM2Percent = lv_label_create(ui_FanControllerScreen);
lv_obj_set_width( ui_PWM2Percent, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PWM2Percent, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PWM2Percent, 103 );
lv_obj_set_y( ui_PWM2Percent, -48 );
lv_obj_set_align( ui_PWM2Percent, LV_ALIGN_CENTER );
lv_label_set_text(ui_PWM2Percent,"50%");
lv_obj_set_style_text_color(ui_PWM2Percent, lv_color_hex(0xEDEDED), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PWM2Percent, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PWM2Percent, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PWM1MaxLabel = lv_label_create(ui_FanControllerScreen);
lv_obj_set_width( ui_PWM1MaxLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PWM1MaxLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PWM1MaxLabel, -34 );
lv_obj_set_y( ui_PWM1MaxLabel, -25 );
lv_obj_set_align( ui_PWM1MaxLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_PWM1MaxLabel,"max");
lv_obj_set_style_text_color(ui_PWM1MaxLabel, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PWM1MaxLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PWM2MaxLabel = lv_label_create(ui_FanControllerScreen);
lv_obj_set_width( ui_PWM2MaxLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PWM2MaxLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PWM2MaxLabel, 211 );
lv_obj_set_y( ui_PWM2MaxLabel, -25 );
lv_obj_set_align( ui_PWM2MaxLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_PWM2MaxLabel,"max");
lv_obj_set_style_text_color(ui_PWM2MaxLabel, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PWM2MaxLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PWM1ZeroLabel = lv_label_create(ui_FanControllerScreen);
lv_obj_set_width( ui_PWM1ZeroLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PWM1ZeroLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PWM1ZeroLabel, -223 );
lv_obj_set_y( ui_PWM1ZeroLabel, 38 );
lv_obj_set_align( ui_PWM1ZeroLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_PWM1ZeroLabel,"0");
lv_obj_set_style_text_color(ui_PWM1ZeroLabel, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PWM1ZeroLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PWM1RPMValueLabel = lv_label_create(ui_FanControllerScreen);
lv_obj_set_width( ui_PWM1RPMValueLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PWM1RPMValueLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PWM1RPMValueLabel, -142 );
lv_obj_set_y( ui_PWM1RPMValueLabel, -4 );
lv_obj_set_align( ui_PWM1RPMValueLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_PWM1RPMValueLabel,"----\nRPM");
lv_obj_set_style_text_color(ui_PWM1RPMValueLabel, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PWM1RPMValueLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_PWM1RPMValueLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PWM2RPMValueLabel = lv_label_create(ui_FanControllerScreen);
lv_obj_set_width( ui_PWM2RPMValueLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PWM2RPMValueLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PWM2RPMValueLabel, 103 );
lv_obj_set_y( ui_PWM2RPMValueLabel, -4 );
lv_obj_set_align( ui_PWM2RPMValueLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_PWM2RPMValueLabel,"----\nRPM");
lv_obj_set_style_text_color(ui_PWM2RPMValueLabel, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PWM2RPMValueLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_PWM2RPMValueLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BackButton5 = lv_btn_create(ui_FanControllerScreen);
lv_obj_set_width( ui_BackButton5, 100);
lv_obj_set_height( ui_BackButton5, 32);
lv_obj_set_x( ui_BackButton5, -183 );
lv_obj_set_y( ui_BackButton5, 132 );
lv_obj_set_align( ui_BackButton5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BackButton5, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BackButton5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_BackButton5, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_BUTTONBG);
ui_object_set_themeable_style_property(ui_BackButton5, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_BUTTONBG);
ui_object_set_themeable_style_property(ui_BackButton5, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_BORDERBG);
ui_object_set_themeable_style_property(ui_BackButton5, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_BORDERBG);
lv_obj_set_style_border_width(ui_BackButton5, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_BackButton5, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_BackButton5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_BackButton5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_BackButton5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BackButton5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_BackButton5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_BackButton5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_BackButton5, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_BackButton5, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BackButton5, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BackLabel4 = lv_label_create(ui_BackButton5);
lv_obj_set_width( ui_BackLabel4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BackLabel4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_BackLabel4, LV_ALIGN_CENTER );
lv_label_set_text(ui_BackLabel4,"BACK");
ui_object_set_themeable_style_property(ui_BackLabel4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TEXT);
ui_object_set_themeable_style_property(ui_BackLabel4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TEXT);

ui_SaveButton4 = lv_btn_create(ui_FanControllerScreen);
lv_obj_set_width( ui_SaveButton4, 100);
lv_obj_set_height( ui_SaveButton4, 32);
lv_obj_set_x( ui_SaveButton4, 0 );
lv_obj_set_y( ui_SaveButton4, 132 );
lv_obj_set_align( ui_SaveButton4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SaveButton4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_SaveButton4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_SaveButton4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_BUTTONBG);
ui_object_set_themeable_style_property(ui_SaveButton4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_BUTTONBG);
ui_object_set_themeable_style_property(ui_SaveButton4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_BORDERBG);
ui_object_set_themeable_style_property(ui_SaveButton4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_BORDERBG);
lv_obj_set_style_border_width(ui_SaveButton4, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_SaveButton4, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_SaveButton4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_SaveButton4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_SaveButton4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SaveButton4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_SaveButton4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_SaveButton4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SaveButton4, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_SaveButton4, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SaveButton4, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SaveLabel4 = lv_label_create(ui_SaveButton4);
lv_obj_set_width( ui_SaveLabel4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SaveLabel4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SaveLabel4, LV_ALIGN_CENTER );
lv_label_set_text(ui_SaveLabel4,"SAVE");
ui_object_set_themeable_style_property(ui_SaveLabel4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TEXT);
ui_object_set_themeable_style_property(ui_SaveLabel4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TEXT);

ui_PWM1LabelFan = lv_label_create(ui_FanControllerScreen);
lv_obj_set_width( ui_PWM1LabelFan, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PWM1LabelFan, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PWM1LabelFan, -142 );
lv_obj_set_y( ui_PWM1LabelFan, -143 );
lv_obj_set_align( ui_PWM1LabelFan, LV_ALIGN_CENTER );
lv_label_set_text(ui_PWM1LabelFan,"FAN #1");
ui_object_set_themeable_style_property(ui_PWM1LabelFan, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TEXT);
ui_object_set_themeable_style_property(ui_PWM1LabelFan, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TEXT);
lv_obj_set_style_text_letter_space(ui_PWM1LabelFan, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_PWM1LabelFan, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PWM1LabelFan, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_PWM1LabelFan, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PWM1LabelFan, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PWM1LabelFan, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_PWM1LabelFan, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_BORDERBG);
ui_object_set_themeable_style_property(ui_PWM1LabelFan, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_BORDERBG);
lv_obj_set_style_border_width(ui_PWM1LabelFan, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_PWM1LabelFan, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_PWM1LabelFan, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PWM1LabelFan, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PWM1LabelFan, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PWM1LabelFan, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PWM2LabelFan = lv_label_create(ui_FanControllerScreen);
lv_obj_set_width( ui_PWM2LabelFan, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PWM2LabelFan, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PWM2LabelFan, 103 );
lv_obj_set_y( ui_PWM2LabelFan, -143 );
lv_obj_set_align( ui_PWM2LabelFan, LV_ALIGN_CENTER );
lv_label_set_text(ui_PWM2LabelFan,"FAN #2");
ui_object_set_themeable_style_property(ui_PWM2LabelFan, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TEXT);
ui_object_set_themeable_style_property(ui_PWM2LabelFan, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TEXT);
lv_obj_set_style_text_letter_space(ui_PWM2LabelFan, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_PWM2LabelFan, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PWM2LabelFan, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_PWM2LabelFan, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PWM2LabelFan, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PWM2LabelFan, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_PWM2LabelFan, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_BORDERBG);
ui_object_set_themeable_style_property(ui_PWM2LabelFan, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_BORDERBG);
lv_obj_set_style_border_width(ui_PWM2LabelFan, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_PWM2LabelFan, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_PWM2LabelFan, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PWM2LabelFan, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PWM2LabelFan, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PWM2LabelFan, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PWM1AutoControl = lv_checkbox_create(ui_FanControllerScreen);
lv_checkbox_set_text(ui_PWM1AutoControl,"Auto");
lv_obj_set_width( ui_PWM1AutoControl, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PWM1AutoControl, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PWM1AutoControl, -142 );
lv_obj_set_y( ui_PWM1AutoControl, 64 );
lv_obj_set_align( ui_PWM1AutoControl, LV_ALIGN_CENTER );
lv_obj_add_state( ui_PWM1AutoControl, LV_STATE_DISABLED );     /// States
lv_obj_add_flag( ui_PWM1AutoControl, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_color(ui_PWM1AutoControl, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PWM1AutoControl, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_PWM1AutoControl, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PWM1AutoControl, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PWM1AutoControl, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PWM1AutoControl, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_PWM1AutoControl, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Container1 = lv_obj_create(ui_FanControllerScreen);
lv_obj_remove_style_all(ui_Container1);
lv_obj_set_width( ui_Container1, 3);
lv_obj_set_height( ui_Container1, 250);
lv_obj_set_x( ui_Container1, 0 );
lv_obj_set_y( ui_Container1, -26 );
lv_obj_set_align( ui_Container1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Container1, lv_color_hex(0x525252), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Container1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Container1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Container1, LV_BORDER_SIDE_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PWM2AutoControl = lv_checkbox_create(ui_FanControllerScreen);
lv_checkbox_set_text(ui_PWM2AutoControl,"Auto");
lv_obj_set_width( ui_PWM2AutoControl, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PWM2AutoControl, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PWM2AutoControl, 103 );
lv_obj_set_y( ui_PWM2AutoControl, 64 );
lv_obj_set_align( ui_PWM2AutoControl, LV_ALIGN_CENTER );
lv_obj_add_state( ui_PWM2AutoControl, LV_STATE_DISABLED );     /// States
lv_obj_add_flag( ui_PWM2AutoControl, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_color(ui_PWM2AutoControl, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PWM2AutoControl, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_PWM2AutoControl, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PWM2AutoControl, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PWM2AutoControl, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PWM2AutoControl, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_PWM2AutoControl, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_PWM1Arc, ui_event_PWM1Arc, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_PWM2Arc, ui_event_PWM2Arc, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BackButton5, ui_event_BackButton5, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SaveButton4, ui_event_SaveButton4, LV_EVENT_ALL, NULL);

}
