// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_IntermediateBlack_screen_init(void)
{
ui_IntermediateBlack = lv_obj_create(NULL);
lv_obj_clear_flag( ui_IntermediateBlack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_IntermediateBlack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_IntermediateBlack, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_IntermediateBlack, ui_event_IntermediateBlack, LV_EVENT_ALL, NULL);

}
