// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_MainScreen_screen_init(void)
{
ui_MainScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_MainScreen, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_MainScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_MainScreen, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelFan1 = lv_obj_create(ui_MainScreen);
lv_obj_set_width( ui_PanelFan1, 111);
lv_obj_set_height( ui_PanelFan1, 111);
lv_obj_set_x( ui_PanelFan1, -178 );
lv_obj_set_y( ui_PanelFan1, -96 );
lv_obj_set_align( ui_PanelFan1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelFan1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PanelFan1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelFan1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelFan1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelFan1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ArcFan1 = lv_arc_create(ui_PanelFan1);
lv_obj_set_width( ui_ArcFan1, 110);
lv_obj_set_height( ui_ArcFan1, 110);
lv_obj_set_align( ui_ArcFan1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ArcFan1, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_arc_set_range(ui_ArcFan1, 0,3000);
lv_arc_set_value(ui_ArcFan1, 0);
lv_arc_set_bg_angles(ui_ArcFan1,0,360);
lv_arc_set_rotation(ui_ArcFan1,270);
lv_obj_set_style_arc_color(ui_ArcFan1, lv_color_hex(0x626262), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_ArcFan1, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_ArcFan1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_ArcFan1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_ArcFan1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_ArcFan1, 10, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_ArcFan1, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_ArcFan1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ArcFan1, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_ArcFan1, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_ArcFan1, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_ArcFan1, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_ArcFan1, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_LabelFan1 = lv_label_create(ui_PanelFan1);
lv_obj_set_width( ui_LabelFan1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelFan1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelFan1, 0 );
lv_obj_set_y( ui_LabelFan1, -24 );
lv_obj_set_align( ui_LabelFan1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelFan1,"FAN #1");
ui_object_set_themeable_style_property(ui_LabelFan1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TEXT);
ui_object_set_themeable_style_property(ui_LabelFan1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TEXT);
lv_obj_set_style_text_letter_space(ui_LabelFan1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_LabelFan1, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelFan1, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_LabelFan1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LabelFan1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LabelFan1, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_LabelFan1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_BORDERBG);
ui_object_set_themeable_style_property(ui_LabelFan1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_BORDERBG);
lv_obj_set_style_border_width(ui_LabelFan1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_LabelFan1, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_LabelFan1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_LabelFan1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_LabelFan1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_LabelFan1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ValueFan1 = lv_label_create(ui_PanelFan1);
lv_obj_set_width( ui_ValueFan1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ValueFan1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ValueFan1, 0 );
lv_obj_set_y( ui_ValueFan1, 8 );
lv_obj_set_align( ui_ValueFan1, LV_ALIGN_CENTER );
lv_label_set_text(ui_ValueFan1,"-");
ui_object_set_themeable_style_property(ui_ValueFan1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TEXT);
ui_object_set_themeable_style_property(ui_ValueFan1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TEXT);
lv_obj_set_style_text_align(ui_ValueFan1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ValueFan1, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RPMFan1 = lv_label_create(ui_PanelFan1);
lv_obj_set_width( ui_RPMFan1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RPMFan1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RPMFan1, 0 );
lv_obj_set_y( ui_RPMFan1, 29 );
lv_obj_set_align( ui_RPMFan1, LV_ALIGN_CENTER );
lv_label_set_text(ui_RPMFan1,"RPM");
ui_object_set_themeable_style_property(ui_RPMFan1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TEXT);
ui_object_set_themeable_style_property(ui_RPMFan1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TEXT);
lv_obj_set_style_text_font(ui_RPMFan1, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_VoltagesLabel = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_VoltagesLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_VoltagesLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_VoltagesLabel, 0 );
lv_obj_set_y( ui_VoltagesLabel, -22 );
lv_obj_set_align( ui_VoltagesLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_VoltagesLabel,"VOLTAGES");
ui_object_set_themeable_style_property(ui_VoltagesLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_LABELTEXT);
ui_object_set_themeable_style_property(ui_VoltagesLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_LABELTEXT);
lv_obj_set_style_text_font(ui_VoltagesLabel, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_VoltagesLabel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_VoltagesLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_BORDERBG);
ui_object_set_themeable_style_property(ui_VoltagesLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_BORDERBG);
lv_obj_set_style_pad_left(ui_VoltagesLabel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_VoltagesLabel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_VoltagesLabel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_VoltagesLabel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelFan2 = lv_obj_create(ui_MainScreen);
lv_obj_set_width( ui_PanelFan2, 111);
lv_obj_set_height( ui_PanelFan2, 111);
lv_obj_set_x( ui_PanelFan2, 177 );
lv_obj_set_y( ui_PanelFan2, -96 );
lv_obj_set_align( ui_PanelFan2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelFan2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PanelFan2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelFan2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelFan2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelFan2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ArcFan2 = lv_arc_create(ui_PanelFan2);
lv_obj_set_width( ui_ArcFan2, 110);
lv_obj_set_height( ui_ArcFan2, 110);
lv_obj_set_align( ui_ArcFan2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ArcFan2, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_arc_set_range(ui_ArcFan2, 0,3000);
lv_arc_set_value(ui_ArcFan2, 0);
lv_arc_set_bg_angles(ui_ArcFan2,0,360);
lv_arc_set_rotation(ui_ArcFan2,270);
lv_obj_set_style_arc_color(ui_ArcFan2, lv_color_hex(0x626262), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_ArcFan2, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_ArcFan2, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_ArcFan2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_ArcFan2, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_ArcFan2, 10, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_ArcFan2, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_ArcFan2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ArcFan2, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_ArcFan2, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_ArcFan2, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_ArcFan2, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_ArcFan2, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_LabelFan2 = lv_label_create(ui_PanelFan2);
lv_obj_set_width( ui_LabelFan2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelFan2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelFan2, 0 );
lv_obj_set_y( ui_LabelFan2, -24 );
lv_obj_set_align( ui_LabelFan2, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelFan2,"FAN #2");
ui_object_set_themeable_style_property(ui_LabelFan2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TEXT);
ui_object_set_themeable_style_property(ui_LabelFan2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TEXT);
lv_obj_set_style_text_font(ui_LabelFan2, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_LabelFan2, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LabelFan2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LabelFan2, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_LabelFan2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_BORDERBG);
ui_object_set_themeable_style_property(ui_LabelFan2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_BORDERBG);
lv_obj_set_style_border_width(ui_LabelFan2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_LabelFan2, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_LabelFan2, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_LabelFan2, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_LabelFan2, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_LabelFan2, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ValueFan2 = lv_label_create(ui_PanelFan2);
lv_obj_set_width( ui_ValueFan2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ValueFan2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ValueFan2, 0 );
lv_obj_set_y( ui_ValueFan2, 8 );
lv_obj_set_align( ui_ValueFan2, LV_ALIGN_CENTER );
lv_label_set_text(ui_ValueFan2,"-");
ui_object_set_themeable_style_property(ui_ValueFan2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TEXT);
ui_object_set_themeable_style_property(ui_ValueFan2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TEXT);
lv_obj_set_style_text_align(ui_ValueFan2, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ValueFan2, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RPMFan2 = lv_label_create(ui_PanelFan2);
lv_obj_set_width( ui_RPMFan2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RPMFan2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RPMFan2, 0 );
lv_obj_set_y( ui_RPMFan2, 29 );
lv_obj_set_align( ui_RPMFan2, LV_ALIGN_CENTER );
lv_label_set_text(ui_RPMFan2,"RPM");
ui_object_set_themeable_style_property(ui_RPMFan2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TEXT);
ui_object_set_themeable_style_property(ui_RPMFan2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TEXT);
lv_obj_set_style_text_font(ui_RPMFan2, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelFan3 = lv_obj_create(ui_MainScreen);
lv_obj_set_width( ui_PanelFan3, 110);
lv_obj_set_height( ui_PanelFan3, 110);
lv_obj_set_x( ui_PanelFan3, -59 );
lv_obj_set_y( ui_PanelFan3, -96 );
lv_obj_set_align( ui_PanelFan3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelFan3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PanelFan3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelFan3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelFan3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelFan3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ArcFan3 = lv_arc_create(ui_PanelFan3);
lv_obj_set_width( ui_ArcFan3, 110);
lv_obj_set_height( ui_ArcFan3, 110);
lv_obj_set_align( ui_ArcFan3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ArcFan3, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_arc_set_range(ui_ArcFan3, 0,5200);
lv_arc_set_value(ui_ArcFan3, 0);
lv_arc_set_bg_angles(ui_ArcFan3,0,360);
lv_arc_set_rotation(ui_ArcFan3,270);
lv_obj_set_style_arc_color(ui_ArcFan3, lv_color_hex(0x626262), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_ArcFan3, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_ArcFan3, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_ArcFan3, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_ArcFan3, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_ArcFan3, 10, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_ArcFan3, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_ArcFan3, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ArcFan3, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_ArcFan3, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_ArcFan3, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_ArcFan3, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_ArcFan3, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_LabelPump1 = lv_label_create(ui_PanelFan3);
lv_obj_set_width( ui_LabelPump1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPump1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPump1, 0 );
lv_obj_set_y( ui_LabelPump1, -24 );
lv_obj_set_align( ui_LabelPump1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPump1,"PUMP #1");
ui_object_set_themeable_style_property(ui_LabelPump1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TEXT);
ui_object_set_themeable_style_property(ui_LabelPump1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TEXT);
lv_obj_set_style_text_font(ui_LabelPump1, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_LabelPump1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LabelPump1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LabelPump1, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_LabelPump1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_BORDERBG);
ui_object_set_themeable_style_property(ui_LabelPump1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_BORDERBG);
lv_obj_set_style_border_width(ui_LabelPump1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_LabelPump1, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_LabelPump1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_LabelPump1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_LabelPump1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_LabelPump1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ValueFan3 = lv_label_create(ui_PanelFan3);
lv_obj_set_width( ui_ValueFan3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ValueFan3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ValueFan3, 0 );
lv_obj_set_y( ui_ValueFan3, 8 );
lv_obj_set_align( ui_ValueFan3, LV_ALIGN_CENTER );
lv_label_set_text(ui_ValueFan3,"-");
ui_object_set_themeable_style_property(ui_ValueFan3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TEXT);
ui_object_set_themeable_style_property(ui_ValueFan3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TEXT);
lv_obj_set_style_text_align(ui_ValueFan3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ValueFan3, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RPMFan3 = lv_label_create(ui_PanelFan3);
lv_obj_set_width( ui_RPMFan3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RPMFan3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RPMFan3, 0 );
lv_obj_set_y( ui_RPMFan3, 29 );
lv_obj_set_align( ui_RPMFan3, LV_ALIGN_CENTER );
lv_label_set_text(ui_RPMFan3,"RPM");
ui_object_set_themeable_style_property(ui_RPMFan3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TEXT);
ui_object_set_themeable_style_property(ui_RPMFan3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TEXT);
lv_obj_set_style_text_font(ui_RPMFan3, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelFan4 = lv_obj_create(ui_MainScreen);
lv_obj_set_width( ui_PanelFan4, 110);
lv_obj_set_height( ui_PanelFan4, 110);
lv_obj_set_x( ui_PanelFan4, 59 );
lv_obj_set_y( ui_PanelFan4, -96 );
lv_obj_set_align( ui_PanelFan4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelFan4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PanelFan4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelFan4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelFan4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelFan4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ArcFan4 = lv_arc_create(ui_PanelFan4);
lv_obj_set_width( ui_ArcFan4, 110);
lv_obj_set_height( ui_ArcFan4, 110);
lv_obj_set_align( ui_ArcFan4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ArcFan4, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_arc_set_range(ui_ArcFan4, 0,5200);
lv_arc_set_value(ui_ArcFan4, 0);
lv_arc_set_bg_angles(ui_ArcFan4,0,360);
lv_arc_set_rotation(ui_ArcFan4,270);
lv_obj_set_style_arc_color(ui_ArcFan4, lv_color_hex(0x626262), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_ArcFan4, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_ArcFan4, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_ArcFan4, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_ArcFan4, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_ArcFan4, 10, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_ArcFan4, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_ArcFan4, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ArcFan4, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_ArcFan4, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_ArcFan4, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_ArcFan4, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_ArcFan4, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_LabelPump2 = lv_label_create(ui_PanelFan4);
lv_obj_set_width( ui_LabelPump2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPump2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPump2, 0 );
lv_obj_set_y( ui_LabelPump2, -24 );
lv_obj_set_align( ui_LabelPump2, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPump2,"PUMP #2");
ui_object_set_themeable_style_property(ui_LabelPump2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TEXT);
ui_object_set_themeable_style_property(ui_LabelPump2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TEXT);
lv_obj_set_style_text_font(ui_LabelPump2, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_LabelPump2, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LabelPump2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LabelPump2, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_LabelPump2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_BORDERBG);
ui_object_set_themeable_style_property(ui_LabelPump2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_BORDERBG);
lv_obj_set_style_border_width(ui_LabelPump2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_LabelPump2, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_LabelPump2, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_LabelPump2, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_LabelPump2, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_LabelPump2, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ValueFan4 = lv_label_create(ui_PanelFan4);
lv_obj_set_width( ui_ValueFan4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ValueFan4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ValueFan4, 0 );
lv_obj_set_y( ui_ValueFan4, 8 );
lv_obj_set_align( ui_ValueFan4, LV_ALIGN_CENTER );
lv_label_set_text(ui_ValueFan4,"-");
ui_object_set_themeable_style_property(ui_ValueFan4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TEXT);
ui_object_set_themeable_style_property(ui_ValueFan4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TEXT);
lv_obj_set_style_text_align(ui_ValueFan4, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ValueFan4, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RPMFan4 = lv_label_create(ui_PanelFan4);
lv_obj_set_width( ui_RPMFan4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RPMFan4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RPMFan4, 0 );
lv_obj_set_y( ui_RPMFan4, 29 );
lv_obj_set_align( ui_RPMFan4, LV_ALIGN_CENTER );
lv_label_set_text(ui_RPMFan4,"RPM");
ui_object_set_themeable_style_property(ui_RPMFan4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TEXT);
ui_object_set_themeable_style_property(ui_RPMFan4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TEXT);
lv_obj_set_style_text_font(ui_RPMFan4, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel12Volts = lv_obj_create(ui_MainScreen);
lv_obj_set_width( ui_Panel12Volts, 95);
lv_obj_set_height( ui_Panel12Volts, 20);
lv_obj_set_x( ui_Panel12Volts, -110 );
lv_obj_set_y( ui_Panel12Volts, 3 );
lv_obj_set_align( ui_Panel12Volts, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel12Volts, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel12Volts, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel12Volts, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Panel12Volts, LV_BORDER_SIDE_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Volts12Value = lv_label_create(ui_Panel12Volts);
lv_obj_set_width( ui_Volts12Value, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Volts12Value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Volts12Value, LV_ALIGN_CENTER );
lv_label_set_text(ui_Volts12Value,"0.00");
ui_object_set_themeable_style_property(ui_Volts12Value, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TEXT);
ui_object_set_themeable_style_property(ui_Volts12Value, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TEXT);
lv_obj_set_style_text_align(ui_Volts12Value, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Volts12Value, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Volts12Label = lv_label_create(ui_Panel12Volts);
lv_obj_set_width( ui_Volts12Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Volts12Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Volts12Label, 40 );
lv_obj_set_y( ui_Volts12Label, 5 );
lv_obj_set_align( ui_Volts12Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Volts12Label,"V");
ui_object_set_themeable_style_property(ui_Volts12Label, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TEXT);
ui_object_set_themeable_style_property(ui_Volts12Label, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TEXT);

ui_Panel5Volts = lv_obj_create(ui_MainScreen);
lv_obj_set_width( ui_Panel5Volts, 95);
lv_obj_set_height( ui_Panel5Volts, 20);
lv_obj_set_x( ui_Panel5Volts, -10 );
lv_obj_set_y( ui_Panel5Volts, 3 );
lv_obj_set_align( ui_Panel5Volts, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel5Volts, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel5Volts, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel5Volts, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel5Volts, lv_color_hex(0x7F7F7F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel5Volts, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Volts5Value = lv_label_create(ui_Panel5Volts);
lv_obj_set_width( ui_Volts5Value, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Volts5Value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Volts5Value, LV_ALIGN_CENTER );
lv_label_set_text(ui_Volts5Value,"0.00");
ui_object_set_themeable_style_property(ui_Volts5Value, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TEXT);
ui_object_set_themeable_style_property(ui_Volts5Value, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TEXT);
lv_obj_set_style_text_align(ui_Volts5Value, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Volts5Value, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Volts5Label = lv_label_create(ui_Panel5Volts);
lv_obj_set_width( ui_Volts5Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Volts5Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Volts5Label, 40 );
lv_obj_set_y( ui_Volts5Label, 5 );
lv_obj_set_align( ui_Volts5Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Volts5Label,"V");
ui_object_set_themeable_style_property(ui_Volts5Label, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TEXT);
ui_object_set_themeable_style_property(ui_Volts5Label, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TEXT);

ui_Panel3V3Volts = lv_obj_create(ui_MainScreen);
lv_obj_set_width( ui_Panel3V3Volts, 95);
lv_obj_set_height( ui_Panel3V3Volts, 20);
lv_obj_set_x( ui_Panel3V3Volts, 90 );
lv_obj_set_y( ui_Panel3V3Volts, 3 );
lv_obj_set_align( ui_Panel3V3Volts, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel3V3Volts, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel3V3Volts, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel3V3Volts, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel3V3Volts, lv_color_hex(0x7F7F7F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel3V3Volts, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Volts3V3Value = lv_label_create(ui_Panel3V3Volts);
lv_obj_set_width( ui_Volts3V3Value, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Volts3V3Value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Volts3V3Value, LV_ALIGN_CENTER );
lv_label_set_text(ui_Volts3V3Value,"0.00");
ui_object_set_themeable_style_property(ui_Volts3V3Value, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TEXT);
ui_object_set_themeable_style_property(ui_Volts3V3Value, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TEXT);
lv_obj_set_style_text_align(ui_Volts3V3Value, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Volts3V3Value, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Volts3V3Label = lv_label_create(ui_Panel3V3Volts);
lv_obj_set_width( ui_Volts3V3Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Volts3V3Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Volts3V3Label, 40 );
lv_obj_set_y( ui_Volts3V3Label, 5 );
lv_obj_set_align( ui_Volts3V3Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Volts3V3Label,"V");
ui_object_set_themeable_style_property(ui_Volts3V3Label, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TEXT);
ui_object_set_themeable_style_property(ui_Volts3V3Label, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TEXT);

ui_PanelAmbient1 = lv_obj_create(ui_MainScreen);
lv_obj_set_width( ui_PanelAmbient1, 90);
lv_obj_set_height( ui_PanelAmbient1, 59);
lv_obj_set_x( ui_PanelAmbient1, 0 );
lv_obj_set_y( ui_PanelAmbient1, 70 );
lv_obj_set_align( ui_PanelAmbient1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelAmbient1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PanelAmbient1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelAmbient1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_PanelAmbient1, LV_BORDER_SIDE_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Ambient1Label = lv_label_create(ui_PanelAmbient1);
lv_obj_set_width( ui_Ambient1Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Ambient1Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Ambient1Label, 0 );
lv_obj_set_y( ui_Ambient1Label, -17 );
lv_obj_set_align( ui_Ambient1Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Ambient1Label,"AMBIENT #1");
ui_object_set_themeable_style_property(ui_Ambient1Label, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_LABELTEXT);
ui_object_set_themeable_style_property(ui_Ambient1Label, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_LABELTEXT);
lv_obj_set_style_text_font(ui_Ambient1Label, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Ambient1Label, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_Ambient1Label, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_BORDERBG);
ui_object_set_themeable_style_property(ui_Ambient1Label, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_BORDERBG);
lv_obj_set_style_pad_left(ui_Ambient1Label, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Ambient1Label, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Ambient1Label, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Ambient1Label, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Temp3Value = lv_label_create(ui_PanelAmbient1);
lv_obj_set_width( ui_Temp3Value, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Temp3Value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Temp3Value, -10 );
lv_obj_set_y( ui_Temp3Value, 12 );
lv_obj_set_align( ui_Temp3Value, LV_ALIGN_CENTER );
lv_label_set_text(ui_Temp3Value,"0.0");
ui_object_set_themeable_style_property(ui_Temp3Value, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TEXT);
ui_object_set_themeable_style_property(ui_Temp3Value, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TEXT);
lv_obj_set_style_text_align(ui_Temp3Value, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Temp3Value, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Temp3Label = lv_label_create(ui_PanelAmbient1);
lv_obj_set_width( ui_Temp3Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Temp3Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Temp3Label, 32 );
lv_obj_set_y( ui_Temp3Label, 16 );
lv_obj_set_align( ui_Temp3Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Temp3Label,"°C");
ui_object_set_themeable_style_property(ui_Temp3Label, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TEXT);
ui_object_set_themeable_style_property(ui_Temp3Label, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TEXT);

ui_PanelAmbient2 = lv_obj_create(ui_MainScreen);
lv_obj_set_width( ui_PanelAmbient2, 90);
lv_obj_set_height( ui_PanelAmbient2, 59);
lv_obj_set_x( ui_PanelAmbient2, 0 );
lv_obj_set_y( ui_PanelAmbient2, 70 );
lv_obj_set_align( ui_PanelAmbient2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_PanelAmbient2, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_PanelAmbient2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PanelAmbient2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelAmbient2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_PanelAmbient2, LV_BORDER_SIDE_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Ambient2Label = lv_label_create(ui_PanelAmbient2);
lv_obj_set_width( ui_Ambient2Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Ambient2Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Ambient2Label, 0 );
lv_obj_set_y( ui_Ambient2Label, -17 );
lv_obj_set_align( ui_Ambient2Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Ambient2Label,"AMBIENT #2");
ui_object_set_themeable_style_property(ui_Ambient2Label, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_LABELTEXT);
ui_object_set_themeable_style_property(ui_Ambient2Label, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_LABELTEXT);
lv_obj_set_style_text_font(ui_Ambient2Label, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Ambient2Label, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_Ambient2Label, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_BORDERBG);
ui_object_set_themeable_style_property(ui_Ambient2Label, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_BORDERBG);
lv_obj_set_style_pad_left(ui_Ambient2Label, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Ambient2Label, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Ambient2Label, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Ambient2Label, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Temp4Value = lv_label_create(ui_PanelAmbient2);
lv_obj_set_width( ui_Temp4Value, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Temp4Value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Temp4Value, -10 );
lv_obj_set_y( ui_Temp4Value, 12 );
lv_obj_set_align( ui_Temp4Value, LV_ALIGN_CENTER );
lv_label_set_text(ui_Temp4Value,"0.0");
ui_object_set_themeable_style_property(ui_Temp4Value, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TEXT);
ui_object_set_themeable_style_property(ui_Temp4Value, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TEXT);
lv_obj_set_style_text_align(ui_Temp4Value, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Temp4Value, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Temp4Label = lv_label_create(ui_PanelAmbient2);
lv_obj_set_width( ui_Temp4Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Temp4Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Temp4Label, 32 );
lv_obj_set_y( ui_Temp4Label, 16 );
lv_obj_set_align( ui_Temp4Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Temp4Label,"°C");
ui_object_set_themeable_style_property(ui_Temp4Label, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TEXT);
ui_object_set_themeable_style_property(ui_Temp4Label, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TEXT);

ui_PanelT1 = lv_obj_create(ui_MainScreen);
lv_obj_set_width( ui_PanelT1, 110);
lv_obj_set_height( ui_PanelT1, 110);
lv_obj_set_x( ui_PanelT1, -172 );
lv_obj_set_y( ui_PanelT1, 98 );
lv_obj_set_align( ui_PanelT1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelT1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PanelT1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelT1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelT1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelT1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ArcT1 = lv_arc_create(ui_PanelT1);
lv_obj_set_width( ui_ArcT1, 110);
lv_obj_set_height( ui_ArcT1, 110);
lv_obj_set_align( ui_ArcT1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ArcT1, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_arc_set_range(ui_ArcT1, 0,50);
lv_arc_set_value(ui_ArcT1, 0);
lv_arc_set_bg_angles(ui_ArcT1,0,360);
lv_arc_set_rotation(ui_ArcT1,270);
lv_obj_set_style_arc_color(ui_ArcT1, lv_color_hex(0x626262), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_ArcT1, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_ArcT1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_ArcT1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_ArcT1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_ArcT1, 10, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_ArcT1, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_ArcT1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ArcT1, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_ArcT1, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_ArcT1, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_ArcT1, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_ArcT1, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_LabelT1 = lv_label_create(ui_PanelT1);
lv_obj_set_width( ui_LabelT1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelT1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelT1, -1 );
lv_obj_set_y( ui_LabelT1, -20 );
lv_obj_set_align( ui_LabelT1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelT1,"TEMP #1");
ui_object_set_themeable_style_property(ui_LabelT1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TEXT);
ui_object_set_themeable_style_property(ui_LabelT1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TEXT);
lv_obj_set_style_text_font(ui_LabelT1, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_LabelT1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LabelT1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LabelT1, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_LabelT1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_BORDERBG);
ui_object_set_themeable_style_property(ui_LabelT1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_BORDERBG);
lv_obj_set_style_border_width(ui_LabelT1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_LabelT1, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_LabelT1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_LabelT1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_LabelT1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_LabelT1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ValueT1 = lv_label_create(ui_PanelT1);
lv_obj_set_width( ui_ValueT1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ValueT1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ValueT1, -1 );
lv_obj_set_y( ui_ValueT1, 7 );
lv_obj_set_align( ui_ValueT1, LV_ALIGN_CENTER );
lv_label_set_text(ui_ValueT1,"0.00");
ui_object_set_themeable_style_property(ui_ValueT1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TEXT);
ui_object_set_themeable_style_property(ui_ValueT1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TEXT);
lv_obj_set_style_text_align(ui_ValueT1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ValueT1, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MetricT1 = lv_label_create(ui_PanelT1);
lv_obj_set_width( ui_MetricT1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MetricT1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MetricT1, -2 );
lv_obj_set_y( ui_MetricT1, 27 );
lv_obj_set_align( ui_MetricT1, LV_ALIGN_CENTER );
lv_label_set_text(ui_MetricT1,"°C");
ui_object_set_themeable_style_property(ui_MetricT1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TEXT);
ui_object_set_themeable_style_property(ui_MetricT1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TEXT);
lv_obj_set_style_text_font(ui_MetricT1, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelT2 = lv_obj_create(ui_MainScreen);
lv_obj_set_width( ui_PanelT2, 110);
lv_obj_set_height( ui_PanelT2, 110);
lv_obj_set_x( ui_PanelT2, 172 );
lv_obj_set_y( ui_PanelT2, 98 );
lv_obj_set_align( ui_PanelT2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelT2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PanelT2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelT2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelT2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelT2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ArcT2 = lv_arc_create(ui_PanelT2);
lv_obj_set_width( ui_ArcT2, 110);
lv_obj_set_height( ui_ArcT2, 110);
lv_obj_set_align( ui_ArcT2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ArcT2, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_arc_set_range(ui_ArcT2, 0,50);
lv_arc_set_value(ui_ArcT2, 0);
lv_arc_set_bg_angles(ui_ArcT2,0,360);
lv_arc_set_rotation(ui_ArcT2,270);
lv_obj_set_style_arc_color(ui_ArcT2, lv_color_hex(0x626262), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_ArcT2, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_ArcT2, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_ArcT2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_ArcT2, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_ArcT2, 10, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_ArcT2, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_ArcT2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ArcT2, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_ArcT2, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_ArcT2, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_ArcT2, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_ArcT2, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_LabelT2 = lv_label_create(ui_PanelT2);
lv_obj_set_width( ui_LabelT2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelT2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelT2, -1 );
lv_obj_set_y( ui_LabelT2, -20 );
lv_obj_set_align( ui_LabelT2, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelT2,"TEMP #2");
ui_object_set_themeable_style_property(ui_LabelT2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TEXT);
ui_object_set_themeable_style_property(ui_LabelT2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TEXT);
lv_obj_set_style_text_font(ui_LabelT2, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_LabelT2, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LabelT2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LabelT2, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_LabelT2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_BORDERBG);
ui_object_set_themeable_style_property(ui_LabelT2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_BORDERBG);
lv_obj_set_style_border_width(ui_LabelT2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_LabelT2, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_LabelT2, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_LabelT2, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_LabelT2, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ValueT2 = lv_label_create(ui_PanelT2);
lv_obj_set_width( ui_ValueT2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ValueT2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ValueT2, -1 );
lv_obj_set_y( ui_ValueT2, 7 );
lv_obj_set_align( ui_ValueT2, LV_ALIGN_CENTER );
lv_label_set_text(ui_ValueT2,"0.00");
ui_object_set_themeable_style_property(ui_ValueT2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TEXT);
ui_object_set_themeable_style_property(ui_ValueT2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TEXT);
lv_obj_set_style_text_align(ui_ValueT2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ValueT2, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RPMT2 = lv_label_create(ui_PanelT2);
lv_obj_set_width( ui_RPMT2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RPMT2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RPMT2, -2 );
lv_obj_set_y( ui_RPMT2, 27 );
lv_obj_set_align( ui_RPMT2, LV_ALIGN_CENTER );
lv_label_set_text(ui_RPMT2,"°C");
ui_object_set_themeable_style_property(ui_RPMT2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TEXT);
ui_object_set_themeable_style_property(ui_RPMT2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TEXT);
lv_obj_set_style_text_font(ui_RPMT2, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SettingsButton = lv_btn_create(ui_MainScreen);
lv_obj_set_width( ui_SettingsButton, 100);
lv_obj_set_height( ui_SettingsButton, 32);
lv_obj_set_x( ui_SettingsButton, -1 );
lv_obj_set_y( ui_SettingsButton, 132 );
lv_obj_set_align( ui_SettingsButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SettingsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_SettingsButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_SettingsButton, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_BUTTONBG);
ui_object_set_themeable_style_property(ui_SettingsButton, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_BUTTONBG);
ui_object_set_themeable_style_property(ui_SettingsButton, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_BORDERBG);
ui_object_set_themeable_style_property(ui_SettingsButton, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_BORDERBG);
lv_obj_set_style_border_width(ui_SettingsButton, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_SettingsButton, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_SettingsButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_SettingsButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_SettingsButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SettingsButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_SettingsButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_SettingsButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SettingsButton, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_SettingsButton, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SettingsButton, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SettingsLabel = lv_label_create(ui_SettingsButton);
lv_obj_set_width( ui_SettingsLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SettingsLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsLabel,"SETTINGS");
ui_object_set_themeable_style_property(ui_SettingsLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TEXT);
ui_object_set_themeable_style_property(ui_SettingsLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TEXT);

ui_TapToSwitchLabel = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_TapToSwitchLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TapToSwitchLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TapToSwitchLabel, -1 );
lv_obj_set_y( ui_TapToSwitchLabel, 34 );
lv_obj_set_align( ui_TapToSwitchLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_TapToSwitchLabel,"tap to switch");
lv_obj_set_style_text_color(ui_TapToSwitchLabel, lv_color_hex(0xBBBBBB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TapToSwitchLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TapToSwitchLabel, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_PanelFan1, ui_event_PanelFan1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_PanelFan2, ui_event_PanelFan2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_PanelAmbient1, ui_event_PanelAmbient1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_PanelAmbient2, ui_event_PanelAmbient2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SettingsButton, ui_event_SettingsButton, LV_EVENT_ALL, NULL);

}
